# Generated by Django 3.1.1 on 2020-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpresoraDjango',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_impresora', models.TextField(max_length=50)),
                ('modelo', models.TextField(max_length=50)),
                ('marca', models.TextField(max_length=50)),
                ('fecha_compra', models.DateField(verbose_name='fecha de compra')),
                ('ultimo_mantenimiento', models.DateField(verbose_name='fecha de ultimo mantenimiento')),
                ('ubicacion_fisica', models.TextField(max_length=50)),
                ('nombre_responsable', models.TextField(max_length=50)),
                ('correo_responsable', models.EmailField(max_length=254)),
                ('ip', models.TextField(max_length=50)),
            ],
        ),
    ]
