# Generated by Django 3.1.1 on 2020-09-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresoradjango',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='impresoradjango',
            name='ultimo_mantenimiento',
            field=models.DateField(verbose_name='fecha del ultimo mantenimiento'),
        ),
    ]
